name: daily

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    # Setting it to 00:00 may cause a huge delay, probably because lots of tasks are being executed at that point.
    - cron: '0 16 * * *' # runs at every 00:00 BeiJing Time
  push:
    branches: [ 'master' ]
    paths:
      - '.github/workflows/daily.yml'
      - 'README.md'
      - 'notes/**'
      - 'algorithms/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # default 1, 0 indicates all history for all branches and tags.

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv markdown
        uv pip install -e . --system

    - name: Update README
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        python scripts/readme/main.py
        #git add -u
        #git commit -m 'Auto-Update README'
        #git push
